apiVersion: v1
kind: Namespace
metadata:
  name: turbo
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kubeturbo
  namespace: turbo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubeturbo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: kubeturbo-git-channel
  namespace: turbo
  annotations:
    apps.open-cluster-management.io/reconcile-rate: low
spec:
  type: Git
  pathname: https://github.com/turbonomic/kubeturbo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: deploy/kubeturbo
  labels:
    app: kubeturbo
  name: kubeturbo-subscription-0
  namespace: turbo
spec:
  channel: turbo/kubeturbo-git-channel
  packageOverrides:
  - packageName: kubeturbo
    packageOverrides:
    - path: spec.serverMeta.turboServer
      value: 'http://10.10.173.110:32730'
  overrides:
  - clusterName: hub
    clusterOverrides:
    - path: spec.targetConfig.targetName
      value: kind-hub
  - clusterName: cluster2
    clusterOverrides:
    - path: spec.targetConfig.targetName
      value: kind-cluster2
  placement:
    placementRef:
      kind: PlacementRule
      name: kubeturbo-placement-0
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: kubeturbo
  name: kubeturbo-placement-0
  namespace: turbo
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"

